server:
  port: 4000
  shutdown: "graceful"

# If you want to use a database then uncomment the `group:, readiness: and include: "db"`
# lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
      show-details: "always"
      group:
       readiness:
        include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info # should we have more?

springdoc:
  packagesToScan: uk.gov.hmcts.reform.dev.controllers
  writer-with-order-by-keys: true

spring:
  config:
    import: "optional:configtree:/mnt/secrets/test/"
  application:
    name: Dev Test
  datasource:
  # Remove default db values and use environment variables instead
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:testdb}
    username: ${DB_USER_NAME:postgres}
    password: ${DB_PASSWORD:postgres}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: taskDbPool
      maxLifetime: 7200000
      connectionTimeout: 30000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            # silence the 'wall-of-text' - unnecessary exception throw about blob types
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true